// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRhlsxY9ZORISru2ztDLDJOfBAi3LhTzw',
    appId: '1:891101504134:web:183ad34c9529a7895ba707',
    messagingSenderId: '891101504134',
    projectId: 'saturnotrcventasdb',
    authDomain: 'saturnotrcventasdb.firebaseapp.com',
    storageBucket: 'saturnotrcventasdb.firebasestorage.app',
    measurementId: 'G-Z66R45FRBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPzC0s0iQZbcHjjIgth7_zML75IEzxwBE',
    appId: '1:891101504134:android:bc451a401f3669df5ba707',
    messagingSenderId: '891101504134',
    projectId: 'saturnotrcventasdb',
    storageBucket: 'saturnotrcventasdb.firebasestorage.app',
  );
}
